version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      # - ./backend/app:/app
      # - ./backend-data:/app/data  # Bind mount for persistent storage
      - type: bind
        source: ./savedImages
        target: /app/savedImages
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - type: bind
        source: ./postgres-data
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - type: bind
        source: ./certbot_data
        target : /etc/nginx/certs
      
    depends_on:
      - backend

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot_data:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 7d & wait $${!}; done;'"

volumes:
  postgres-data:
    driver: local
  myapp: